import os
import time
import io
import logging
from datetime import datetime

import requests
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors, utils
from reportlab.lib.units import mm

logger = logging.getLogger(__name__)


def _fetch_image_stream(url, timeout=8):
    """Download image and return BytesIO or None on failure."""
    try:
        resp = requests.get(url, timeout=timeout)
        resp.raise_for_status()
        return io.BytesIO(resp.content)
    except Exception:
        logger.exception("Failed to fetch image %s", url)
        return None


def _make_image_flowable(img_stream, max_width_mm=160):
    """
    Create a reportlab Image flowable from a BytesIO stream.
    max_width_mm: maximum width in millimeters to fit on page.
    """
    try:
        img_reader = utils.ImageReader(img_stream)
        iw, ih = img_reader.getSize()
        max_width = max_width_mm * mm
        if iw <= 0:
            return None
        scale = 1.0
        if iw > max_width:
            scale = max_width / iw
        width = iw * scale
        height = ih * scale
        img_stream.seek(0)
        return Image(img_stream, width=width, height=height)
    except Exception:
        logger.exception("Failed to create image flowable")
        return None


def generate_visit_pdf(visit_info, items, generated_dir, report_id=None):
    """
    Generate a PDF report for the visit.
    - visit_info: dict with keys like 'building_name', 'email', etc.
    - items: list of item dicts; each item may include 'description' and 'image_urls' (list).
    - generated_dir: directory to write the PDF into (will be created if missing).
    - report_id: optional string used in filename.
    Returns: (pdf_path, pdf_filename)
    """
    os.makedirs(generated_dir, exist_ok=True)
    timestamp = int(time.time())
    filename = f"report_{report_id or timestamp}.pdf"
    pdf_path = os.path.join(generated_dir, filename)

    try:
        doc = SimpleDocTemplate(pdf_path, pagesize=A4,
                                rightMargin=20 * mm, leftMargin=20 * mm,
                                topMargin=20 * mm, bottomMargin=20 * mm)

        styles = getSampleStyleSheet()
        title_style = styles['Heading1']
        normal = styles['BodyText']
        small = ParagraphStyle('small', parent=normal, fontSize=9)

        story = []

        # Header
        title_text = visit_info.get('building_name') or "Site Visit Report"
        story.append(Paragraph(title_text, title_style))
        story.append(Spacer(1, 6))

        meta_lines = []
        meta_lines.append(("Date:", datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")))
        if visit_info.get('email'):
            meta_lines.append(("Technician:", visit_info.get('email')))
        if visit_info.get('building_address'):
            meta_lines.append(("Address:", visit_info.get('building_address')))

        # Table for metadata
        meta_table_data = [[Paragraph(f"<b>{k}</b>", small), Paragraph(str(v), small)] for k, v in meta_lines]
        if meta_table_data:
            t = Table(meta_table_data, colWidths=[40 * mm, None])
            t.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            story.append(t)
            story.append(Spacer(1, 8))

        # Items
        if not items:
            story.append(Paragraph("No items recorded.", normal))
        else:
            for idx, it in enumerate(items, start=1):
                heading = Paragraph(f"<b>{idx}. {it.get('title', it.get('description', 'Item'))}</b>", styles['Heading4'])
                story.append(heading)
                desc = it.get('description', '')
                if desc:
                    story.append(Paragraph(desc, normal))
                story.append(Spacer(1, 4))

                # Inline images (if any)
                image_urls = it.get('image_urls') or []
                for img_url in image_urls:
                    stream = _fetch_image_stream(img_url)
                    if not stream:
                        continue
                    img_flow = _make_image_flowable(stream)
                    if img_flow:
                        story.append(img_flow)
                        story.append(Spacer(1, 6))

                story.append(Spacer(1, 8))

        # Footer note
        story.append(Spacer(1, 12))
        story.append(Paragraph("Generated by Injaaz", small))

        doc.build(story)
        logger.info("Generated PDF: %s", pdf_path)
        return pdf_path, filename
    except Exception:
        logger.exception("Failed to generate PDF")
        # ensure no empty or broken file left
        try:
            if os.path.exists(pdf_path) and os.path.getsize(pdf_path) == 0:
                os.remove(pdf_path)
        except Exception:
            pass
        raise