# Injaaz Application - Windows Setup Script
# This script automates the setup process for local development

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Injaaz Application - Setup Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if Python is installed
Write-Host "Checking Python installation..." -ForegroundColor Yellow
try {
    $pythonVersion = python --version 2>&1
    Write-Host "✓ Python found: $pythonVersion" -ForegroundColor Green
} catch {
    Write-Host "✗ Python is not installed or not in PATH" -ForegroundColor Red
    Write-Host "  Please install Python from https://www.python.org/downloads/" -ForegroundColor Yellow
    exit 1
}

# Check if Node.js is installed
Write-Host "Checking Node.js installation..." -ForegroundColor Yellow
try {
    $nodeVersion = node --version 2>&1
    $npmVersion = npm --version 2>&1
    Write-Host "✓ Node.js found: $nodeVersion" -ForegroundColor Green
    Write-Host "✓ npm found: $npmVersion" -ForegroundColor Green
} catch {
    Write-Host "✗ Node.js is not installed or not in PATH" -ForegroundColor Red
    Write-Host "  Please install Node.js from https://nodejs.org/" -ForegroundColor Yellow
    exit 1
}

# Create virtual environment if it doesn't exist
Write-Host ""
Write-Host "Setting up Python virtual environment..." -ForegroundColor Yellow
if (Test-Path "venv") {
    Write-Host "✓ Virtual environment already exists" -ForegroundColor Green
} else {
    Write-Host "Creating virtual environment..." -ForegroundColor Yellow
    python -m venv venv
    Write-Host "✓ Virtual environment created" -ForegroundColor Green
}

# Activate virtual environment
Write-Host ""
Write-Host "Activating virtual environment..." -ForegroundColor Yellow
if ($env:VIRTUAL_ENV) {
    Write-Host "✓ Virtual environment is already activated" -ForegroundColor Green
} else {
    & .\venv\Scripts\Activate.ps1
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Virtual environment activated" -ForegroundColor Green
    } else {
        Write-Host "⚠ Could not activate virtual environment automatically" -ForegroundColor Yellow
        Write-Host "  Please run: .\venv\Scripts\Activate.ps1" -ForegroundColor Yellow
        Write-Host "  If you get an execution policy error, run:" -ForegroundColor Yellow
        Write-Host "  Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser" -ForegroundColor Yellow
    }
}

# Upgrade pip
Write-Host ""
Write-Host "Upgrading pip..." -ForegroundColor Yellow
python -m pip install --upgrade pip --quiet
Write-Host "✓ pip upgraded" -ForegroundColor Green

# Install Python dependencies
Write-Host ""
Write-Host "Installing Python dependencies..." -ForegroundColor Yellow
if (Test-Path "requirements-prods.txt") {
    pip install -r requirements-prods.txt
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Python dependencies installed" -ForegroundColor Green
    } else {
        Write-Host "✗ Failed to install Python dependencies" -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host "✗ requirements-prods.txt not found" -ForegroundColor Red
    exit 1
}

# Install Node.js dependencies
Write-Host ""
Write-Host "Installing Node.js dependencies..." -ForegroundColor Yellow
if (Test-Path "package.json") {
    npm install
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Node.js dependencies installed" -ForegroundColor Green
    } else {
        Write-Host "⚠ Failed to install Node.js dependencies (non-critical)" -ForegroundColor Yellow
    }
} else {
    Write-Host "⚠ package.json not found, skipping Node.js dependencies" -ForegroundColor Yellow
}

# Create .env file if it doesn't exist
Write-Host ""
Write-Host "Checking environment configuration..." -ForegroundColor Yellow
if (Test-Path ".env") {
    Write-Host "✓ .env file already exists" -ForegroundColor Green
} else {
    Write-Host "Creating .env file from template..." -ForegroundColor Yellow
    
    # Generate secure random keys
    $secretKey = python -c "import secrets; print(secrets.token_urlsafe(32))" 2>&1
    $jwtSecretKey = python -c "import secrets; print(secrets.token_urlsafe(32))" 2>&1
    
    $envContent = @"
# ============================================================
# Injaaz Application - Environment Configuration
# ============================================================
# Generated by setup script - Review and update as needed

# FLASK ENVIRONMENT
FLASK_ENV=development
DEBUG=true

# SECURITY KEYS (Generated automatically - CHANGE IN PRODUCTION!)
SECRET_KEY=$secretKey
JWT_SECRET_KEY=$jwtSecretKey

# DATABASE (SQLite will be used automatically for local dev)
# DATABASE_URL=sqlite:///injaaz.db

# CLOUDINARY (Optional for local dev)
# Get credentials from: https://cloudinary.com/console
# CLOUDINARY_CLOUD_NAME=your-cloud-name
# CLOUDINARY_API_KEY=your-api-key
# CLOUDINARY_API_SECRET=your-api-secret

# APPLICATION URL
APP_BASE_URL=http://localhost:5000

# REDIS (Optional - only needed for rate limiting)
# REDIS_URL=redis://localhost:6379

# EMAIL SETTINGS (Optional)
# MAIL_SERVER=smtp.gmail.com
# MAIL_PORT=587
# MAIL_USERNAME=your-email@gmail.com
# MAIL_PASSWORD=your-app-password
# MAIL_USE_TLS=true
# MAIL_DEFAULT_SENDER=noreply@injaaz.com
"@
    
    $envContent | Out-File -FilePath ".env" -Encoding UTF8
    Write-Host "✓ .env file created" -ForegroundColor Green
    Write-Host "  Please review and update .env file as needed" -ForegroundColor Yellow
}

# Initialize database
Write-Host ""
Write-Host "Initializing database..." -ForegroundColor Yellow
if (Test-Path "scripts\init_db.py") {
    python scripts\init_db.py
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Database initialized" -ForegroundColor Green
    } else {
        Write-Host "⚠ Database initialization had issues (may already be initialized)" -ForegroundColor Yellow
    }
} else {
    Write-Host "⚠ init_db.py not found, skipping database initialization" -ForegroundColor Yellow
}

# Summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Review and update .env file if needed" -ForegroundColor White
Write-Host "2. Activate virtual environment: .\venv\Scripts\Activate.ps1" -ForegroundColor White
Write-Host "3. Start the application: python Injaaz.py" -ForegroundColor White
Write-Host "   Or use: .\start.bat" -ForegroundColor White
Write-Host "4. Open http://localhost:5000 in your browser" -ForegroundColor White
Write-Host "5. Login with admin credentials:" -ForegroundColor White
Write-Host "   Username: admin" -ForegroundColor White
Write-Host "   Password: Admin@123" -ForegroundColor White
Write-Host "   ⚠ IMPORTANT: Change this password immediately!" -ForegroundColor Red
Write-Host ""
Write-Host "For more details, see SETUP.md" -ForegroundColor Cyan
Write-Host ""
