"""Generate test PDFs for all HR forms with realistic sample data."""
import sys, os, io
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from module_hr.hr_pdf_builder import build_hr_pdf

outdir = os.path.join(os.path.dirname(__file__), '..', 'test_output', 'all_forms_test')
os.makedirs(outdir, exist_ok=True)

# Tiny 1×1 transparent PNG encoded as base64 (placeholder signature)
SIG = ('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAAA'
       'yCAYAAAC+jd/lAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJl'
       'YWR5ccllPAAAACZJREFUeNrs0AENAAAAwqD3T20PB'
       'hAAAAAAAAAAAAAAAAAAAAAAgAEAAwABAAGnZwAAAABJRU5ErkJggg==')

FORMS = {
    'commencement': {
        'employee_name': 'Ahmed Al Mansouri',
        'position': 'Facility Manager',
        'contacts': '050-1234567',
        'department': 'Operations',
        'organization': 'INJAAZ LLC',
        'date_of_joining': '2026-03-01',
        'bank_name': 'Emirates NBD',
        'bank_branch': 'Ajman Main',
        'account_number': '1234567890123',
        'employee_signature': SIG,
        'employee_sign_date': '2026-03-12',
        'reporting_to_name': 'Mohammed Al Rashid',
        'reporting_to_designation': 'Operations Director',
        'reporting_to_contact': '050-9876543',
        'reporting_to_signature': SIG,
        'reporting_sign_date': '2026-03-12',
    },
    'duty_resumption': {
        'requester': 'Self',
        'employee_name': 'Ahmed Al Mansouri',
        'employee_id': 'EMP-001',
        'job_title': 'Facility Manager',
        'company': 'INJAAZ LLC',
        'leave_started': '2026-02-10',
        'leave_ended': '2026-02-20',
        'planned_resumption_date': '2026-02-21',
        'actual_resumption_date': '2026-02-21',
        'note': 'Returned from annual leave.',
        'employee_signature': SIG,
        'sign_date': '2026-02-21',
        'line_manager_remarks': 'Approved. Welcome back.',
        'hr_signature': SIG,
        'gm_signature': SIG,
    },
    'passport_release': {
        'passport_form_type': 'release',
        'form_date': '2026-03-12',
        'requester': 'Self',
        'employee_name': 'Ahmed Al Mansouri',
        'employee_id': 'EMP-001',
        'job_title': 'Facility Manager',
        'project': 'Ajman Site',
        'release_date': '2026-03-14',
        'purpose_of_release': 'Travel to home country for family emergency.',
        'employee_signature': SIG,
        'hr_signature': SIG,
        'gm_signature': SIG,
    },
    'visa_renewal': {
        'form_date': '2026-03-12',
        'employee_name': 'Ahmed Al Mansouri',
        'employee_id': 'EMP-001',
        'employer': 'INJAAZ LLC',
        'position': 'Facility Manager',
        'years_completed': '2',
        'decision': 'continue',
        'decision_display': 'Continue employment and renew visa',
        'employee_signature': SIG,
        'hr_signature': SIG,
        'gm_signature': SIG,
    },
    'station_clearance': {
        'employee_name': 'Ahmed Al Mansouri',
        'employee_id': 'EMP-001',
        'position': 'Facility Manager',
        'department': 'Operations',
        'section': 'CAFM',
        'employment_date': '2024-03-01',
        'type_of_departure': 'resignation',
        'last_working_date': '2026-03-31',
        'tasks_handed_over': True,
        'documents_handed_over': True,
        'files_handed_over': True,
        'keys_returned': True,
        'toolbox_returned': True,
        'access_card_returned': True,
        'email_cancelled': True,
        'software_hardware_returned': True,
        'laptop_returned': True,
        'file_shifted': True,
        'dues_paid': True,
        'medical_card_returned': True,
        'eos_transfer': True,
        'remarks': 'All clearance items completed successfully.',
        'employee_signature': SIG,
        'hr_signature': SIG,
    },
    'grievance': {
        'complainant_name': 'Ahmed Al Mansouri',
        'complainant_id': 'EMP-001',
        'complainant_designation': 'Facility Manager',
        'complainant_contact': '050-1234567',
        'date_of_incident': '2026-03-10',
        'shift_time': '08:00-17:00',
        'issue_location': 'site',
        'second_party_name': 'Ali Hassan',
        'second_party_id': 'EMP-002',
        'second_party_department': 'Maintenance',
        'place_of_incident': 'Workshop',
        'second_party_shift': '08:00-17:00',
        'second_party_contact': '050-7654321',
        'complaint_description': 'Verbal altercation during shift handover.',
        'witnesses': 'Khalid Omar',
        'who_informed': 'Line Manager',
        'attachment': 'None',
        'hr_remarks': 'Under investigation.',
        'gm_remarks': 'Noted.',
        'complainant_signature': SIG,
        'hr_signature': SIG,
        'gm_signature': SIG,
    },
    'interview_assessment': {
        'candidate_name': 'Fatima Al Zahra',
        'position_title': 'HR Coordinator',
        'academic_qualification': 'Bachelor of Business Administration',
        'age': '28',
        'gender': 'F',
        'marital_status': 'Single',
        'dependents': '0',
        'nationality': 'UAE',
        'current_job_title': 'HR Assistant',
        'years_experience': '4',
        'current_salary': '6000',
        'expected_salary': '8000',
        'interview_date': '2026-03-12',
        'interview_by': 'Mohammed Al Rashid',
        'rating_turnout': 'outstanding',
        'rating_confidence': 'v_good',
        'rating_mental_alertness': 'good',
        'rating_maturity': 'v_good',
        'rating_communication': 'outstanding',
        'rating_technical': 'good',
        'rating_training': 'v_good',
        'rating_experience': 'good',
        'rating_overall': 'v_good',
        'assessment_professional': 'Strong academic background and 4 years of relevant HR experience.',
        'assessment_personality': 'Confident, professional, and a good team player.',
        'eligibility': 'YES',
        'job_recommended_for': 'HR Coordinator',
        'interviewer_name': 'Mohammed Al Rashid',
        'interviewer_title': 'Operations Director',
        'interviewer_signature': SIG,
        'hr_signature': SIG,
        'gm_signature': SIG,
    },
    'staff_appraisal': {
        'employee_name': 'Ahmed Al Mansouri',
        'employee_id': 'EMP-001',
        'department': 'Operations',
        'position': 'Facility Manager',
        'appraisal_period': 'Jan 2026 - Mar 2026',
        'reviewer': 'Mohammed Al Rashid',
        'rating_punctuality': '4',
        'rating_job_knowledge': '5',
        'rating_quality': '4',
        'rating_productivity': '4',
        'rating_communication': '5',
        'rating_teamwork': '4',
        'rating_problem_solving': '4',
        'rating_adaptability': '3',
        'rating_leadership': '4',
        'total_score': '4.0',
        'employee_strengths': 'Excellent communication and technical knowledge.',
        'employee_signature': SIG,
        'hr_signature': SIG,
        'gm_signature': SIG,
    },
    'performance_evaluation': {
        'employee_name': 'Ahmed Al Mansouri',
        'employee_id': 'EMP-001',
        'department': 'Operations',
        'designation': 'Facility Manager',
        'date_of_evaluation': '2026-03-12',
        'date_of_joining': '2024-03-01',
        'evaluation_done_by': 'Mohammed Al Rashid',
        'score_01': '8', 'score_02': '9', 'score_03': '8',
        'score_04': '7', 'score_05': '8', 'score_06': '9',
        'score_07': '8', 'score_08': '8', 'score_09': '7', 'score_10': '8',
        'overall_score': '80',
        'evaluator_name': 'Mohammed Al Rashid',
        'evaluator_designation': 'Operations Director',
        'evaluator_observation': 'Strong performance across all areas.',
        'area_of_concern': 'Time management during peak periods.',
        'training_required': 'Advanced Facility Management Certification',
        'employee_comments': 'Committed to improving time management skills.',
        'gm_remarks': 'Good performance. Recommend salary increment.',
        'hr_remarks': 'Salary revision effective April 2026.',
        'employee_signature': SIG,
        'evaluator_signature': SIG,
        'hr_signature': SIG,
        'gm_signature': SIG,
    },
    'contract_renewal': {
        'employee_name': 'Ahmed Al Mansouri',
        'employee_id': 'EMP-001',
        'department': 'Operations',
        'designation': 'Facility Manager',
        'date_of_joining': '2024-03-01',
        'contract_end_date': '2026-03-31',
        'date_of_evaluation': '2026-03-12',
        'evaluation_by': 'Mohammed Al Rashid',
        'rating_01a': '5', 'rating_01b': '4', 'rating_01c': '5',
        'rating_01d': '4', 'rating_01e': '4',
        'rating_02a': '5', 'rating_02b': '4', 'rating_02c': '5',
        'rating_02d': '4', 'rating_02e': '5',
        'rating_03a': '5', 'rating_03b': '4', 'rating_03c': '4',
        'rating_03d': '4', 'rating_03e': '5',
        'rating_04a': '5', 'rating_04b': '5', 'rating_04c': '4',
        'decision': 'renew',
        'strength': 'Exceptional technical skills and leadership ability.',
        'areas_for_improvement': 'Documentation could be more detailed.',
        'evaluator_signature': SIG,
        'hr_signature': SIG,
        'gm_signature': SIG,
    },
}

ok_count = 0
fail_count = 0
for form_type, fd in FORMS.items():
    out = os.path.join(outdir, f'{form_type}.pdf')
    try:
        ok = build_hr_pdf(form_type, fd, out, submission_id=f'HR-TEST-{form_type.upper()[:8]}')
        status = 'OK  ' if ok else 'FAIL'
        if ok:
            ok_count += 1
        else:
            fail_count += 1
    except Exception as e:
        status = 'ERR '
        fail_count += 1
        print(f'  ERROR: {form_type}: {e}')
        continue
    print(f'  {status}: {form_type}')

print(f'\nResults: {ok_count} OK, {fail_count} FAIL')
print(f'Output: {os.path.abspath(outdir)}')
